repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
# Temporalmente desactivado hasta configurar correctamente el entorno
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.10.0
#     hooks:
#     -   id: mypy
#         files: ^(app|tests)/.*\.py$
