"""Add full_name to users table

Revision ID: 1524cd005e2c
Revises:
Create Date: 2025-08-23 23:15:32.020065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1524cd005e2c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=True))

    # Step 2: Update existing records with a default value
    op.execute("UPDATE users SET full_name = 'Usuario' WHERE full_name IS NULL")

    # Step 3: Make the column NOT NULL
    op.alter_column("users", "full_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
