"""Agregar tablas de habitaciones, productos, pedidos y tarifas

Revision ID: 414d25e789d9
Revises: aef86e3a39de
Create Date: 2025-08-23 11:49:56.225122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414d25e789d9'
down_revision: Union[str, Sequence[str], None] = 'aef86e3a39de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitaciones',
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('precio_noche', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('capacidad_personas', sa.Integer(), nullable=False),
    sa.Column('tiene_bano_privado', sa.Boolean(), nullable=False),
    sa.Column('tiene_balcon', sa.Boolean(), nullable=False),
    sa.Column('tiene_vista_mar', sa.Boolean(), nullable=False),
    sa.Column('permite_mascotas', sa.Boolean(), nullable=False),
    sa.Column('wifi_incluido', sa.Boolean(), nullable=False),
    sa.Column('aire_acondicionado', sa.Boolean(), nullable=False),
    sa.Column('television', sa.Boolean(), nullable=False),
    sa.Column('minibar', sa.Boolean(), nullable=False),
    sa.Column('caja_fuerte', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitaciones_id'), 'habitaciones', ['id'], unique=False)
    op.create_index(op.f('ix_habitaciones_numero'), 'habitaciones', ['numero'], unique=True)
    op.create_table('productos',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria'), 'productos', ['categoria'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('tarifas',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_habitacion', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('dias_semana', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarifas_id'), 'tarifas', ['id'], unique=False)
    op.create_index(op.f('ix_tarifas_nombre'), 'tarifas', ['nombre'], unique=False)
    op.create_index(op.f('ix_tarifas_tipo_habitacion'), 'tarifas', ['tipo_habitacion'], unique=False)
    op.create_table('pedidos',
    sa.Column('hospedaje_id', sa.Integer(), nullable=False),
    sa.Column('numero_habitacion', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospedaje_id'], ['hospedajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_numero_habitacion'), 'pedidos', ['numero_habitacion'], unique=False)
    op.create_table('lineas_pedido',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones_linea', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_pedido_id'), 'lineas_pedido', ['id'], unique=False)
    op.create_index(op.f('ix_lineas_pedido_pedido_id'), 'lineas_pedido', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineas_pedido_pedido_id'), table_name='lineas_pedido')
    op.drop_index(op.f('ix_lineas_pedido_id'), table_name='lineas_pedido')
    op.drop_table('lineas_pedido')
    op.drop_index(op.f('ix_pedidos_numero_habitacion'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_tarifas_tipo_habitacion'), table_name='tarifas')
    op.drop_index(op.f('ix_tarifas_nombre'), table_name='tarifas')
    op.drop_index(op.f('ix_tarifas_id'), table_name='tarifas')
    op.drop_table('tarifas')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_habitaciones_numero'), table_name='habitaciones')
    op.drop_index(op.f('ix_habitaciones_id'), table_name='habitaciones')
    op.drop_table('habitaciones')
    # ### end Alembic commands ###
