"""Agregar campo servicio_lavanderia a habitaciones

Revision ID: 7848d470c270
Revises: 414d25e789d9
Create Date: 2025-08-23 11:50:41.297536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7848d470c270'
down_revision: Union[str, Sequence[str], None] = '414d25e789d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habitaciones', sa.Column('servicio_lavanderia', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habitaciones', 'servicio_lavanderia')
    # ### end Alembic commands ###
