"""Crear tablas iniciales

Revision ID: aef86e3a39de
Revises:
Create Date: 2025-08-22 14:24:44.604190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef86e3a39de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospedajes',
    sa.Column('nombre_huesped', sa.String(length=100), nullable=False),
    sa.Column('email_huesped', sa.String(length=100), nullable=True),
    sa.Column('telefono_huesped', sa.String(length=20), nullable=True),
    sa.Column('documento_identidad', sa.String(length=50), nullable=True),
    sa.Column('numero_habitacion', sa.String(length=10), nullable=False),
    sa.Column('tipo_habitacion', sa.String(length=50), nullable=False),
    sa.Column('fecha_check_in', sa.Date(), nullable=False),
    sa.Column('fecha_check_out', sa.Date(), nullable=False),
    sa.Column('precio_por_noche', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('numero_noches', sa.Integer(), nullable=False),
    sa.Column('total_hospedaje', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospedajes_id'), 'hospedajes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('puesto', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_hospedajes_id'), table_name='hospedajes')
    op.drop_table('hospedajes')
    # ### end Alembic commands ###
